Cargo.lock, crates/compiler/parser/Cargo.toml, crates/compiler/parser/src/lexer.rs, crates/compiler/parser/src/lib.rs, crates/compiler/parser/src/tokens.rs
=> feat: add lexer

.trunk/trunk.yaml, Cargo.lock, crates/compiler/parser/Cargo.toml, crates/compiler/parser/README.md, crates/compiler/parser/src/lexer.rs, crates/compiler/parser/src/lib.rs, crates/compiler/parser/src/parser.rs, crates/compiler/parser/src/snapshots/cairo_m_compiler_parser__parser__tests__simple_let_error.snap
=> feat(compiler): add boilerplate code for parser testing

.trunk/trunk.yaml, Cargo.lock, Cargo.toml, crates/runner/Cargo.toml, crates/runner/src/lib.rs, crates/runner/src/memory/mod.rs
=> feat(vm): Memory

crates/runner/src/lib.rs, crates/runner/src/vm/instructions/mod.rs, crates/runner/src/vm/mod.rs
=> feat(vm): init instructions struct

crates/runner/src/vm/instructions/mod.rs, crates/runner/src/vm/instructions/store.rs, crates/runner/src/vm/mod.rs
=> feat(vm): add store instructions

crates/compiler/semantic/src/type_resolution.rs, crates/compiler/semantic/src/types/types_test.rs
=> feat(compiler): implement type inference in variable resolution

crates/runner/src/vm/instructions/mod.rs, crates/runner/src/vm/mod.rs
=> feat(vm): main loop

crates/runner/src/vm/instructions/jump.rs, crates/runner/src/vm/instructions/store.rs
=> doc(vm): simplify instructions doc

crates/runner/src/vm/instructions/jnz.rs, crates/runner/src/vm/instructions/mod.rs
=> feat(vm): add jnz instructions

crates/runner/src/memory/mod.rs, crates/runner/src/vm/mod.rs
=> feat(vm): memory trace

.trunk/configs/osv-scanner.toml, Cargo.lock, Cargo.toml, crates/compiler/codegen/Cargo.toml, crates/compiler/mir/Cargo.toml, crates/compiler/parser/Cargo.toml, crates/compiler/semantic/Cargo.toml, crates/prover/Cargo.toml, crates/prover/src/components/memory.rs, crates/prover/src/components/mod.rs, crates/prover/src/components/multiple_constraints.rs, crates/prover/src/components/single_constraint.rs, crates/prover/src/components/single_constraint_with_relation.rs, crates/prover/src/errors.rs, crates/prover/src/lib.rs, crates/prover/src/preprocessed.rs, crates/prover/src/prover.rs, crates/prover/src/relations.rs, crates/prover/src/verifier.rs, crates/prover/tests/prover.rs
=> Prover scaffolding

crates/compiler/codegen/README.md, crates/compiler/codegen/session.md, crates/compiler/codegen/src/builder.rs, crates/compiler/codegen/src/layout.rs, crates/compiler/codegen/tests/snapshots/codegen_tests__arithmetic_add_two_numbers.snap, crates/compiler/codegen/tests/snapshots/codegen_tests__arithmetic_subtract_numbers.snap, crates/compiler/codegen/tests/snapshots/codegen_tests__control_flow_if_else.snap, crates/compiler/codegen/tests/snapshots/codegen_tests__control_flow_if_else_with_merge.snap, crates/compiler/codegen/tests/snapshots/codegen_tests__control_flow_simple_if.snap, crates/compiler/codegen/tests/snapshots/codegen_tests__functions_fib.snap, crates/compiler/codegen/tests/snapshots/codegen_tests__functions_simple_call.snap, crates/compiler/codegen/tests/snapshots/codegen_tests__simple_function_simple.snap, crates/compiler/codegen/tests/snapshots/codegen_tests__simple_function_with_params.snap, crates/compiler/codegen/tests/snapshots/codegen_tests__simple_function_with_return.snap, crates/compiler/mir/src/ir_generation/tests/mir_generation_tests.rs, crates/compiler/mir/src/ir_generation/tests/snapshots/cairo_m_compiler_mir__ir_generation__tests__mir_generation_tests__functions_fib.snap, crates/compiler/mir/src/ir_generation/tests/test_cases/functions/fib.cm
=> fix(compiler): fix fp offsets for return statements

.github/workflows/benchmark-pr.yml, .github/workflows/benchmarks.yml, .trunk/configs/.yamllint.yaml
=> chore(ci): add runner benches to CI

crates/runner/benches/fibonacci_loop.cm, crates/runner/benches/vm_benchmark.rs, crates/runner/tests/diff_tests.rs
=> bench(vm): use compiled file

Cargo.lock, Cargo.toml, crates/runner/Cargo.toml, crates/runner/src/main.rs
=> feat(vm): use anyhow for CLI

Cargo.lock, crates/prover/Cargo.toml, crates/prover/src/adapter/memory.rs, crates/prover/src/components/memory.rs, crates/prover/src/components/mod.rs, crates/prover/src/components/multiple_constraints.rs, crates/prover/src/components/single_constraint.rs, crates/prover/src/components/single_constraint_with_relation.rs, crates/prover/src/lib.rs, crates/prover/src/preprocessed/range_check_20.rs, crates/prover/src/prover.rs, crates/prover/src/relations.rs, crates/prover/src/verifier.rs, crates/prover/tests/prover.rs
=> feat(prover): implement memory component

Cargo.lock, crates/prover/Cargo.toml, crates/prover/src/components/memory.rs, crates/prover/src/components/mod.rs, crates/prover/src/lib.rs, crates/prover/src/preprocessed/range_check_20.rs
=> feat(prover): serialize proof struct

Cargo.lock, crates/prover/Cargo.toml, crates/prover/benches/range_check_init.rs, crates/prover/src/components/mod.rs, crates/prover/src/preprocessed/mod.rs, crates/prover/src/preprocessed/range_check/mod.rs, crates/prover/src/preprocessed/range_check/range_check_20.rs
- **Create a mod for range_check and make sure rc_20 hardcodes 20 everywhere**
- **Add bench for range_check init method**
=> feat(prover): Range check minor refacto

crates/common/src/lib.rs, crates/common/src/state.rs, crates/prover/src/adapter/io.rs, crates/prover/src/adapter/memory.rs, crates/prover/src/adapter/mod.rs, crates/prover/tests/fibonacci_trace_test.rs, crates/runner/src/vm/instructions/call.rs, crates/runner/src/vm/instructions/call_tests.rs, crates/runner/src/vm/instructions/jnz.rs, crates/runner/src/vm/instructions/jump.rs, crates/runner/src/vm/instructions/mod.rs, crates/runner/src/vm/instructions/store.rs, crates/runner/src/vm/mod.rs, crates/runner/src/vm/state.rs, crates/runner/src/vm/vm_tests.rs
=> feat(prover): instantiate ProverInput from RunnerOutput

crates/prover/src/components/mod.rs, crates/prover/src/lib.rs, crates/prover/src/prover.rs, crates/prover/src/public_data.rs, crates/prover/src/relations.rs, crates/prover/src/verifier.rs
=> feat(prover): add register relation

crates/runner/benches/vm_benchmark.rs
=> bench: remove io

crates/prover/src/utils.rs
=> bug(prover): fix sub underflow

Cargo.lock, Cargo.toml, README.md, crates/prover/Cargo.toml, crates/prover/src/main.rs, crates/prover/src/prover.rs, crates/prover/tests/prover.rs
=> feat(prover): profile

crates/prover/benches/prover_memory_benchmark.rs, crates/prover/benches/prover_speed_benchmark.rs, crates/prover/src/lib.rs, crates/prover/src/main.rs, crates/prover/src/prover.rs, crates/prover/src/prover_config.rs, crates/prover/src/verifier.rs, crates/prover/tests/prover.rs
=> feat(prover): add PCS config

Cargo.toml, LICENSE, LICENSE-APACHE, LICENSE-MIT
Add MIT + Apache 2.0 dual license files and update Cargo.toml to address GitHub issue #146.
Resolves #146
=> Add dual licensing

crates/prover/benches/prover_memory_benchmark.rs, crates/prover/benches/prover_speed_benchmark.rs, crates/prover/src/adapter/mod.rs, crates/prover/src/debug_tools/relation_tracker.rs, crates/prover/src/main.rs, crates/prover/src/public_data.rs, crates/prover/tests/fibonacci_trace_test.rs, crates/prover/tests/prover.rs, crates/runner/src/lib.rs, crates/runner/src/vm/mod.rs, crates/runner/src/vm/vm_tests.rs
=> feat(prover): add public addresses

Cargo.lock, crates/cairo-m-ls/tests/e2e/hover/snapshots/e2e__hover__cross_file_hover__hover_on_imported_constant.snap, crates/cairo-m-ls/tests/e2e/hover/snapshots/e2e__hover__cross_file_hover__hover_on_imported_function.snap, crates/common/src/instruction.rs, crates/common/tests/instruction_tests.rs, crates/compiler/codegen/src/lib.rs, crates/prover/Cargo.toml, crates/prover/src/adapter/io.rs, crates/prover/src/adapter/memory.rs, crates/prover/src/adapter/mod.rs, crates/prover/src/components/opcodes/call_abs_imm.rs, crates/prover/src/components/opcodes/jmp_abs_imm.rs, crates/prover/src/components/opcodes/jmp_rel_imm.rs, crates/prover/src/components/opcodes/jnz_fp_imm.rs, crates/prover/src/components/opcodes/mod.rs, crates/prover/src/components/opcodes/ret.rs, crates/prover/src/components/opcodes/store_add_fp_fp.rs, crates/prover/src/components/opcodes/store_add_fp_imm.rs, crates/prover/src/components/opcodes/store_div_fp_fp.rs, crates/prover/src/components/opcodes/store_div_fp_imm.rs, crates/prover/src/components/opcodes/store_double_deref_fp.rs, crates/prover/src/components/opcodes/store_imm.rs, crates/prover/src/components/opcodes/store_mul_fp_fp.rs, crates/prover/src/components/opcodes/store_mul_fp_imm.rs, crates/prover/src/components/opcodes/store_sub_fp_fp.rs, crates/prover/src/components/opcodes/store_sub_fp_imm.rs, crates/prover/src/utils/execution_bundle.rs, crates/runner/src/memory/mod.rs, crates/runner/src/vm/instructions/mod.rs
=> feat(prover): Adapt Prover Adapter and Bundles for U32 Support

crates/prover/src/components/opcodes/assert_eq_fp_fp.rs, crates/prover/src/components/opcodes/assert_eq_fp_imm.rs, crates/prover/src/components/opcodes/mod.rs
=> feat(prover): add assert_eq components

crates/prover/src/components/opcodes/mod.rs, crates/prover/src/components/opcodes/u32_store_add_fp_imm.rs, crates/prover/src/debug_tools/assert_constraints.rs, crates/prover/src/debug_tools/relation_tracker.rs
=> feat(prover): add u32_store_add_fp_imm

crates/prover/src/components/opcodes/mod.rs, crates/prover/src/components/opcodes/u32_store_mul_fp_imm.rs, crates/prover/src/debug_tools/assert_constraints.rs, crates/prover/src/debug_tools/relation_tracker.rs
=> feat(prover): add u32_store_mul_fp_imm

crates/prover/src/components/opcodes/mod.rs, crates/prover/src/components/opcodes/u32_store_add_fp_imm.rs, crates/prover/src/components/opcodes/u32_store_div_fp_imm.rs, crates/prover/src/components/opcodes/u32_store_eq_fp_fp.rs, crates/prover/src/components/opcodes/u32_store_eq_fp_imm.rs, crates/prover/src/components/opcodes/u32_store_imm.rs, crates/prover/src/components/opcodes/u32_store_lt_fp_fp.rs, crates/prover/src/components/opcodes/u32_store_lt_fp_imm.rs, crates/prover/src/components/opcodes/u32_store_mul_fp_imm.rs, crates/prover/src/debug_tools/assert_constraints.rs, crates/prover/src/debug_tools/relation_tracker.rs, crates/prover/tests/prover.rs, test_data/functions/all_opcodes.cm
=> feat(prover): add u32_store_lt_{fp_fp/imm}

crates/compiler/codegen/src/builder/felt.rs, crates/compiler/codegen/src/generator.rs, crates/compiler/codegen/tests/snapshots/mdtest_codegen_snapshots@complex_expressions_in_cairo_m___assertions.snap, crates/compiler/mir/src/instruction.rs, crates/compiler/mir/src/lowering/expr.rs, crates/compiler/mir/src/lowering/stmt.rs, crates/compiler/mir/src/lowering/value_based_tests.rs, crates/compiler/mir/src/passes/local_cse.rs, crates/compiler/mir/src/passes/sroa.rs, crates/compiler/mir/tests/snapshots/mdtest_mir_snapshots@complex_expressions_in_cairo_m___assertions.snap, crates/compiler/semantic/src/builtins.rs, crates/compiler/semantic/src/lib.rs, crates/compiler/semantic/src/type_resolution.rs, crates/compiler/semantic/src/validation/scope_check.rs, crates/compiler/semantic/src/validation/type_validator.rs, crates/compiler/semantic/tests/common/snapshots/parameterized__functions::builtins::test_assert_built_in_parameterized.snap, crates/compiler/semantic/tests/functions/builtins.rs, crates/compiler/semantic/tests/functions/mod.rs, cspell.yaml, mdtest/01-basics/06-expressions.md, test_data/functions/all_opcodes.cm
adds `assert` builtin function `assert(val_0 == val_1)`
=> feat(compiler): builtin assert function

cairo-m-project/cairom.toml, cairo-m-project/src/library/utils.cm, cairo-m-project/src/main.cm, cairo-m-project/src/math.cm, crates/compiler/tests/mod.rs
=> dev: remove root cairo-m-project example
